### ISSUE TITLE
Support gzip-ed bit files or disable flashing of unknown files

### ISSUE THREAD

**Issue by dpavlin** [kost/fujprog#7]
https://github.com/kost/fujprog/blob/e0cedeb90e3691e18356cbd1757df73d3d1b1639/fujprog.c#L3112

Why is good idea to flash random unknown files instead of loading them to ram? This is sure way to corrupt your flashed image if you specify gziped bit file (which is supporetd by esp32ecp5).

On that note, I would love to have support of bziped bit files. Sure, I can do something like

```
gzip -cd ulx3s_85f_minimig_ps2kbd.bit.gz | fujprog
```

But it would be nice to at least warn me that file is gziped instead of flashing it to fpga board.

**Comment by kost** [comment]
It is intended behaviour.
Idea here was if file type is not recognized to automatically flash it to flash, so any roms with different extensions (snes, nes, etc) will be automatically flashed where they should be. But you still get nice warning about that:
```
Could not automatically guess type by extension: @0x0.
Automatically targeting flash and setting image type.
Erasing sectors, please wait.
```

If you want to force file type, you can always say -T bit in the command line.

Regarding gzipped bitstreams, not sure if we want add another dependency. Isn't ecppack --compress is better anyway?
